language: r
sudo: true
cache: packages
warnings_are_errors: true

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh github_package hadley/testthat
  - ./travis-tool.sh github_package Bioconductor-mirror/BiocInstaller
  - ./travis-tool.sh github_package joey711/phyloseq
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update

r_packages:
  - phyloseq

r_binary_packages:
  - reshape2
  - dplyr
  - data.table
  - ggplot2
  - Cairo
  - scales

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
