language: r

sudo: false
cache: packages

warnings_are_errors: true

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps

r_packages:
  - phyloseq

r_binary_packages:
  - reshape2
  - dplyr
  - data.table
  - Cairo

r_github_packages:
  - hadley/testthat
  - jimhester/covr
  - jimhester/lintr
  - hadley/ggplot2

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
