language: r

sudo: true
cache: packages

warnings_are_errors: true

apt_packages:
  - libicu-dev
  - libxml2-dev

r_packages:
  - phyloseq

r_binary_packages:
  - curl
  - openssl
  - xml2
  - evaluate
  - praise
  - stringi
  - reshape2
  - dplyr
  - data.table
  - Cairo

r_github_packages:
  - hadley/testthat
  - jimhester/covr
  - jimhester/lintr
  - hadley/ggplot2

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
